//! The seeded generator behind every adversary choice ([F15 §6.4] "Determinism").
//!
//! xoshiro256** seeded through SplitMix64: small, fast, and identical on every target, so a seed replays byte-identically
//! wherever the simulator runs. The crate has no dependency that could supply it (PLAN §2.2: `moirai-vfs` only), and
//! nothing here is cryptographic.

/// A deterministic 64-bit generator (xoshiro256**).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Rng {
    s: [u64; 4],
}

/// One SplitMix64 step: the seeding function of xoshiro, also used to derive sub-seeds.
pub(crate) fn splitmix(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

impl Rng {
    /// A generator whose whole output is a function of `seed`.
    pub fn new(seed: u64) -> Rng {
        let mut sm = seed;
        let mut s = [0u64; 4];
        for word in &mut s {
            *word = splitmix(&mut sm);
        }
        if s == [0; 4] {
            s[0] = 1;
        }
        Rng { s }
    }

    /// The next 64 bits.
    pub fn next_u64(&mut self) -> u64 {
        let result = self.s[1].wrapping_mul(5).rotate_left(7).wrapping_mul(9);
        let t = self.s[1] << 17;
        self.s[2] ^= self.s[0];
        self.s[3] ^= self.s[1];
        self.s[1] ^= self.s[2];
        self.s[0] ^= self.s[3];
        self.s[2] ^= t;
        self.s[3] = self.s[3].rotate_left(45);
        result
    }

    /// A uniform value in `0..n` (unbiased, by rejection); `n` must be positive. `u64::MAX` as `n` means "any `u64`".
    pub fn below(&mut self, n: u64) -> u64 {
        assert!(n > 0, "Rng::below(0)");
        if n == u64::MAX {
            return self.next_u64();
        }
        if n.is_power_of_two() {
            return self.next_u64() & (n - 1);
        }
        let zone = u64::MAX - (u64::MAX % n);
        loop {
            let x = self.next_u64();
            if x < zone {
                return x % n;
            }
        }
    }

    /// `true` with probability `per_million / 10^6`; consumes nothing when the rate is 0, so a fault-free
    /// configuration draws no values for its fault sites.
    pub fn chance(&mut self, per_million: u32) -> bool {
        per_million != 0 && self.below(1_000_000) < u64::from(per_million)
    }

    /// Fills `buf` with generated bytes.
    pub fn fill(&mut self, buf: &mut [u8]) {
        for chunk in buf.chunks_mut(8) {
            let w = self.next_u64().to_le_bytes();
            chunk.copy_from_slice(&w[..chunk.len()]);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn replays_and_differs() {
        let mut a = Rng::new(7);
        let mut b = Rng::new(7);
        let mut c = Rng::new(8);
        let xs: Vec<u64> = (0..16).map(|_| a.next_u64()).collect();
        let ys: Vec<u64> = (0..16).map(|_| b.next_u64()).collect();
        let zs: Vec<u64> = (0..16).map(|_| c.next_u64()).collect();
        assert_eq!(xs, ys);
        assert_ne!(xs, zs);
    }

    #[test]
    fn below_is_in_range_and_rates_are_exact_at_the_ends() {
        let mut r = Rng::new(1);
        for n in [1u64, 2, 3, 7, 1000, 1 << 40, u64::MAX - 1] {
            for _ in 0..100 {
                assert!(r.below(n) < n);
            }
        }
        let before = r.clone();
        assert!(!r.chance(0));
        assert_eq!(r, before, "a zero rate draws nothing");
        assert!(r.chance(1_000_000));
        let mut buf = [0u8; 13];
        r.fill(&mut buf);
        assert!(buf.iter().any(|&b| b != 0));
    }
}
