//! AI-attribution markers: the rules of `.githooks/commit-msg` (WP-03), applied by `xtask gate` to every commit of
//! `master..HEAD` (WP-02), by `xtask hook pr-body` to a pull request's title and body, and by `xtask ci commits` to
//! every commit of a pull request or a push (WP-04). docs/m0/PLAN.md §3.2 item 7; AGENTS.md "Git"; authors.md §5
//! item 4 (the three layers).
//!
//! This is a byte-for-byte port of the hook's POSIX awk program, which runs in the C locale: text is compared after
//! ASCII lower-casing, and "word" characters are `[a-z0-9_]`. Rules, case-insensitive:
//! 1. any `Co-authored-by` trailer, whoever it names;
//! 2. "Generated with" or "Generated by" followed on the same line by an AI tool name;
//! 3. `noreply@anthropic.com` and other addresses at AI vendors, and the GitHub noreply addresses of AI agents;
//! 4. Claude, Anthropic, Codex, OpenAI or Copilot in a trailer or an attribution line;
//! 5. the robot emoji U+1F916.
//!
//! The hook and this module are tested with the same cases (`.githooks/test-hooks.sh` and the tests below).

/// One refused line.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Refusal {
    pub rule: u8,
    pub what: &'static str,
    pub place: String,
    pub text: String,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "rule {}, {}: {}: {}",
            self.rule, self.what, self.place, self.text
        )
    }
}

const ROBOT: &[u8] = "\u{1F916}".as_bytes();

const TOOLS: &[&str] = &[
    "claude",
    "claudecode",
    "anthropic",
    "codex",
    "openai",
    "open ai",
    "chatgpt",
    "copilot",
    "gemini",
    "bard",
    "cursor ai",
    "cursor agent",
    "devin",
    "aider",
    "windsurf",
    "codeium",
    "tabnine",
    "codewhisperer",
    "amazon q",
    "google jules",
    "grok",
    "llama",
    "mistral",
    "deepseek",
    "qwen",
    "sourcegraph cody",
];

const NAMES: &[&str] = &[
    "claude",
    "claudecode",
    "anthropic",
    "codex",
    "openai",
    "open ai",
    "copilot",
];

const VENDOR_DOMAINS: &[&str] = &[
    "anthropic.com",
    "claude.ai",
    "claude.com",
    "openai.com",
    "chatgpt.com",
    "cursor.com",
    "cursor.sh",
    "anysphere.co",
    "codeium.com",
    "windsurf.com",
    "tabnine.com",
    "x.ai",
    "mistral.ai",
    "deepmind.com",
    "deepseek.com",
    "cognition.ai",
    "devin.ai",
    "aider.chat",
];

const BOTS: &[&str] = &[
    "copilot",
    "copilot-swe-agent",
    "claude",
    "claude-code",
    "claude-bot",
    "codex",
    "openai",
    "openai-codex",
    "chatgpt-codex-connector",
    "devin-ai-integration",
    "cursor",
    "cursor-agent",
    "cursoragent",
    "gemini-code-assist",
    "google-labs-jules",
    "aider",
];

const VERBS: &[&str] = &[
    "generated",
    "written",
    "authored",
    "co-authored",
    "coauthored",
    "co-written",
    "assisted",
    "created",
    "made",
    "produced",
    "drafted",
    "powered",
    "built",
    "prepared",
    "coded",
    "developed",
    "composed",
    "reviewed",
];

const PREPS: &[&str] = &["with", "by", "using", "via", "through"];

fn word(b: u8) -> bool {
    b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'
}

fn addr_char(b: u8) -> bool {
    b.is_ascii_lowercase() || b.is_ascii_digit() || matches!(b, b'.' | b'_' | b'%' | b'+' | b'-')
}

fn find_all<'a>(hay: &'a [u8], needle: &'a [u8]) -> impl Iterator<Item = usize> + 'a {
    (0..=hay.len().saturating_sub(needle.len()))
        .filter(move |&i| hay.len() >= needle.len() && &hay[i..i + needle.len()] == needle)
}

/// `B0 alt B1` over `t`, where `B0 = (^|[^a-z0-9_])` and `B1 = ([^a-z0-9_]|$)`.
fn has_word(t: &[u8], w: &str) -> bool {
    let w = w.as_bytes();
    find_all(t, w)
        .any(|i| (i == 0 || !word(t[i - 1])) && t.get(i + w.len()).is_none_or(|&c| !word(c)))
}

/// `gpt[-0-9a-z.]*` between word boundaries, with the regex's backtracking.
fn has_gpt(t: &[u8]) -> bool {
    find_all(t, b"gpt").any(|i| {
        if i > 0 && word(t[i - 1]) {
            return false;
        }
        let start = i + 3;
        let mut end = start;
        while end < t.len()
            && (t[end].is_ascii_lowercase()
                || t[end].is_ascii_digit()
                || t[end] == b'-'
                || t[end] == b'.')
        {
            end += 1;
        }
        (start..=end)
            .rev()
            .any(|k| t.get(k).is_none_or(|&c| !word(c)))
    })
}

fn has_tool(t: &[u8]) -> bool {
    TOOLS.iter().any(|w| has_word(t, w)) || has_gpt(t)
}

fn has_name(t: &[u8]) -> bool {
    NAMES.iter().any(|w| has_word(t, w))
}

/// `^[ \t]*co-?authored[-_ ]?by[ \t]*[:=]`
fn is_coauthor(t: &[u8]) -> bool {
    let mut i = skip_blank(t, 0);
    let Some(r) = t[i..].strip_prefix(b"co") else {
        return false;
    };
    i = t.len() - r.len();
    if t.get(i) == Some(&b'-') {
        i += 1;
    }
    let Some(r) = t[i..].strip_prefix(b"authored") else {
        return false;
    };
    i = t.len() - r.len();
    if matches!(t.get(i), Some(b'-' | b'_' | b' ')) && t[i + 1..].starts_with(b"by") {
        i += 1;
    }
    let Some(r) = t[i..].strip_prefix(b"by") else {
        return false;
    };
    i = skip_blank(t, t.len() - r.len());
    matches!(t.get(i), Some(b':' | b'='))
}

fn skip_blank(t: &[u8], mut i: usize) -> usize {
    while matches!(t.get(i), Some(b' ' | b'\t')) {
        i += 1;
    }
    i
}

/// Rule 2: the leftmost `generated[-_ \t]+(with|by)`, then an AI tool anywhere after it.
fn generated_with_tool(t: &[u8]) -> bool {
    for i in find_all(t, b"generated") {
        let mut j = i + b"generated".len();
        let s = j;
        while matches!(t.get(j), Some(b'-' | b'_' | b' ' | b'\t')) {
            j += 1;
        }
        if j == s {
            continue;
        }
        let rest_at = if t[j..].starts_with(b"with") {
            j + 4
        } else if t[j..].starts_with(b"by") {
            j + 2
        } else {
            continue;
        };
        return has_tool(&t[rest_at..]);
    }
    false
}

/// Rule 3.
fn has_vendor_address(t: &[u8]) -> bool {
    // [a-z0-9._%+-]+@([a-z0-9-]+\.)*(domain)([^a-z0-9.-]|$)
    for at in find_all(t, b"@") {
        if at == 0 || !addr_char(t[at - 1]) {
            continue;
        }
        let mut end = at + 1;
        while end < t.len()
            && (t[end].is_ascii_lowercase()
                || t[end].is_ascii_digit()
                || t[end] == b'.'
                || t[end] == b'-')
        {
            end += 1;
        }
        let host = &t[at + 1..end];
        for d in VENDOR_DOMAINS {
            let d = d.as_bytes();
            if host.ends_with(d) {
                let prefix = &host[..host.len() - d.len()];
                if prefix.is_empty() || labels_with_dots(prefix) {
                    return true;
                }
            }
        }
    }
    // (^|[^a-z0-9._%+-])([0-9]+\+)?(bot)(\[bot\])?@users\.noreply\.github\.com
    for i in find_all(t, b"@users.noreply.github.com") {
        let local = &t[..i];
        let local = local.strip_suffix(b"[bot]").unwrap_or(local);
        for b in BOTS {
            let Some(before) = local.strip_suffix(b.as_bytes()) else {
                continue;
            };
            if before.last().is_none_or(|&c| !addr_char(c)) {
                return true;
            }
            if let Some(nums) = before.strip_suffix(b"+") {
                let digits = nums.iter().rev().take_while(|c| c.is_ascii_digit()).count();
                if digits > 0
                    && nums[..nums.len() - digits]
                        .last()
                        .is_none_or(|&c| !addr_char(c))
                {
                    return true;
                }
            }
        }
    }
    // (^|[^a-z0-9._%+-])copilot@github\.com
    find_all(t, b"copilot@github.com").any(|i| i == 0 || !addr_char(t[i - 1]))
}

/// `([a-z0-9-]+\.)+`
fn labels_with_dots(p: &[u8]) -> bool {
    if p.last() != Some(&b'.') {
        return false;
    }
    p[..p.len() - 1].split(|&c| c == b'.').all(|l| {
        !l.is_empty()
            && l.iter()
                .all(|&c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == b'-')
    })
}

/// `^[ \t]*[a-z0-9][a-z0-9-]*[ \t]*:`; returns the token when the line has that shape.
fn trailer_token(t: &[u8]) -> Option<&[u8]> {
    let s = skip_blank(t, 0);
    let first = *t.get(s)?;
    if !(first.is_ascii_lowercase() || first.is_ascii_digit()) {
        return None;
    }
    let mut e = s + 1;
    while e < t.len() && (t[e].is_ascii_lowercase() || t[e].is_ascii_digit() || t[e] == b'-') {
        e += 1;
    }
    let c = skip_blank(t, e);
    (t.get(c) == Some(&b':')).then_some(&t[s..e])
}

/// `^[ \t]*[a-z0-9][a-z0-9-]*-(by|with)[ \t]*:`
fn is_by_with_trailer(t: &[u8]) -> bool {
    match trailer_token(t) {
        Some(tok) => {
            (tok.len() > 3 && tok.ends_with(b"-by")) || (tok.len() > 5 && tok.ends_with(b"-with"))
        }
        None => false,
    }
}

/// `^[ \t]*[a-z][a-z0-9+.-]*://`
fn is_url(t: &[u8]) -> bool {
    let s = skip_blank(t, 0);
    if !t.get(s).is_some_and(u8::is_ascii_lowercase) {
        return false;
    }
    let mut e = s + 1;
    while e < t.len()
        && (t[e].is_ascii_lowercase()
            || t[e].is_ascii_digit()
            || matches!(t[e], b'+' | b'.' | b'-'))
    {
        e += 1;
    }
    t[e..].starts_with(b"://")
}

/// `^[^a-z0-9]*(verbs)[ \t]+(with|by|using|via|through)([^a-z0-9_]|$)`
fn is_attribution(t: &[u8]) -> bool {
    let Some(p) = t
        .iter()
        .position(|&c| c.is_ascii_lowercase() || c.is_ascii_digit())
    else {
        return false;
    };
    let rest = &t[p..];
    VERBS.iter().any(|v| {
        let Some(after) = rest.strip_prefix(v.as_bytes()) else {
            return false;
        };
        let sp = after
            .iter()
            .take_while(|&&c| c == b' ' || c == b'\t')
            .count();
        if sp == 0 {
            return false;
        }
        let after = &after[sp..];
        PREPS.iter().any(|w| {
            after
                .strip_prefix(w.as_bytes())
                .is_some_and(|r| r.first().is_none_or(|&c| !word(c)))
        })
    })
}

/// `^[^[:alnum:][:space:]]+ -+ >8 -+$`; returns the prefix (git's comment string).
fn scissors_prefix(line: &[u8]) -> Option<&[u8]> {
    let sp = line.iter().position(|&c| c == b' ')?;
    let pfx = &line[..sp];
    if pfx.is_empty()
        || pfx
            .iter()
            .any(|c| c.is_ascii_alphanumeric() || c.is_ascii_whitespace())
    {
        return None;
    }
    let rest = &line[sp + 1..];
    let d1 = rest.iter().take_while(|&&c| c == b'-').count();
    if d1 == 0 {
        return None;
    }
    let rest = rest[d1..].strip_prefix(b" >8 ")?;
    (!rest.is_empty() && rest.iter().all(|&c| c == b'-')).then_some(pfx)
}

fn git_text_after_cut(s: &[u8], cutpfx: &[u8]) -> bool {
    if s.iter().all(|&c| c == b' ' || c == b'\t') {
        return true;
    }
    if s.starts_with(cutpfx) {
        return true;
    }
    if matches!(s.first(), Some(b' ' | b'+' | b'-' | b'@' | b'\\')) {
        return true;
    }
    const HEADS: &[&str] = &[
        "diff ",
        "index ",
        "new file mode ",
        "deleted file mode ",
        "old mode ",
        "new mode ",
        "similarity index ",
        "dissimilarity index ",
        "rename from ",
        "rename to ",
        "copy from ",
        "copy to ",
        "Binary files ",
    ];
    HEADS.iter().any(|h| s.starts_with(h.as_bytes()))
}

/// Checks a commit message (or a pull request's title and body) as the `commit-msg` hook does. `git_trailers` is
/// git's own trailer parse of the message (`%(trailers:only,unfold)` or `git interpret-trailers --parse`), empty when
/// unknown; `comment` is the comment prefix (`#` unless `core.commentString` says otherwise).
pub fn check_message(msg: &str, git_trailers: &str, comment: &str) -> Vec<Refusal> {
    let mut lines: Vec<&[u8]> = Vec::new();
    let mut after: Vec<bool> = Vec::new();
    let mut cut: Option<Vec<u8>> = None;
    for raw in msg.as_bytes().split(|&c| c == b'\n') {
        let line = raw.strip_suffix(b"\r").unwrap_or(raw);
        if cut.is_none()
            && let Some(p) = scissors_prefix(line)
        {
            cut = Some(p.to_vec());
            continue;
        }
        if let Some(p) = &cut
            && git_text_after_cut(line, p)
        {
            continue;
        }
        lines.push(line);
        after.push(cut.is_some());
    }
    // `split` yields one empty piece after a final newline; awk sees no record there.
    if msg.ends_with('\n')
        && lines.last().is_some_and(|l| l.is_empty())
        && !after.last().copied().unwrap_or(false)
    {
        lines.pop();
        after.pop();
    }

    let cc = comment.as_bytes();
    let mut para = vec![0usize; lines.len()];
    let mut p = 0;
    let mut inpara = false;
    for (i, l) in lines.iter().enumerate() {
        if after[i] {
            continue;
        }
        if l.iter().all(|&c| c == b' ' || c == b'\t') || (!cc.is_empty() && l.starts_with(cc)) {
            inpara = false;
            continue;
        }
        if !inpara {
            p += 1;
            inpara = true;
        }
        para[i] = p;
    }
    let lastp = p;

    let mut out = Vec::new();
    let mut report = |rule: u8, what: &'static str, place: String, text: &[u8]| {
        out.push(Refusal {
            rule,
            what,
            place,
            text: String::from_utf8_lossy(text).into_owned(),
        });
    };
    for (i, l) in lines.iter().enumerate() {
        let t = l.to_ascii_lowercase();
        let place = format!("line {}", i + 1);
        if is_coauthor(&t) {
            report(1, "Co-authored-by trailer", place.clone(), l);
        }
        if generated_with_tool(&t) {
            report(2, "Generated with/by an AI tool", place.clone(), l);
        }
        if has_vendor_address(&t) {
            report(3, "AI-vendor address", place.clone(), l);
        }
        let trailer = is_by_with_trailer(&t)
            || (lastp > 1 && para[i] == lastp && trailer_token(&t).is_some() && !is_url(&t));
        if has_name(&t) {
            if trailer {
                report(4, "AI name in a trailer", place.clone(), l);
            } else if is_attribution(&t) {
                report(4, "AI name in an attribution line", place.clone(), l);
            }
        }
        if find_all(l, ROBOT).next().is_some() {
            report(5, "robot emoji U+1F916", place, l);
        }
    }
    if out.is_empty() {
        for g in git_trailers.split('\n') {
            let t = g.as_bytes().to_ascii_lowercase();
            if is_coauthor(&t) {
                out.push(Refusal {
                    rule: 1,
                    what: "Co-authored-by trailer",
                    place: "git trailer".into(),
                    text: g.to_string(),
                });
            } else if has_name(&t) {
                out.push(Refusal {
                    rule: 4,
                    what: "AI name in a trailer",
                    place: "git trailer".into(),
                    text: g.to_string(),
                });
            }
        }
    }
    out
}

/// Rule 3 over a commit's author or committer identity (`Name <email>`).
pub fn check_identity(role: &str, ident: &str) -> Vec<Refusal> {
    let t = ident.as_bytes().to_ascii_lowercase();
    if has_vendor_address(&t) {
        vec![Refusal {
            rule: 3,
            what: "AI-vendor address",
            place: role.to_string(),
            text: ident.to_string(),
        }]
    } else {
        Vec::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rules(msg: &str) -> Vec<u8> {
        check_message(msg, "", "#").iter().map(|r| r.rule).collect()
    }

    /// The refusal cases of `.githooks/test-hooks.sh`, with the rule each must be refused by.
    const REFUSED: &[(&str, u8)] = &[
        (
            "WP-01: add the workspace\n\nCo-authored-by: Claude <noreply@anthropic.com>\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\nCo-authored-by: Jane Example <jane@example.invalid>\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\nco-authored-by: someone <someone@example.invalid>\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\nCO-AUTHORED-BY: SOMEONE <SOMEONE@EXAMPLE.INVALID>\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\nCo-authored-by: someone <someone@example.invalid>\n\nMore text.\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\n\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)\n",
            5,
        ),
        (
            "WP-01: add the workspace\n\nGenerated with Claude Code\n",
            2,
        ),
        (
            "WP-01: add the workspace\n\nThis change was generated by openai codex.\n",
            2,
        ),
        (
            "WP-01: add the workspace\n\nGenerated with GitHub Copilot\n",
            2,
        ),
        ("WP-01: add the workspace\n\nGenerated by ChatGPT\n", 2),
        (
            "WP-01: add the workspace\n\nGenerated with GPT-5 in a chat.\n",
            2,
        ),
        ("Generated by Gemini\n", 2),
        (
            "WP-01: add the workspace\n\nContact noreply@anthropic.com for details.\n",
            3,
        ),
        (
            "WP-01: add the workspace\n\nSigned-off-by: Bot <codex@openai.com>\n",
            3,
        ),
        (
            "WP-01: add the workspace\n\nThanks: 198982749+Copilot@users.noreply.github.com\n",
            3,
        ),
        (
            "WP-01: add the workspace\n\nSee copilot-swe-agent[bot]@users.noreply.github.com\n",
            3,
        ),
        ("WP-01: add the workspace\n\nAssisted-by: Claude\n", 4),
        (
            "WP-01: add the workspace\n\nBody text.\n\nReviewed-by: oPeNaI cOdEx\n",
            4,
        ),
        (
            "WP-01: add the workspace\n\nHelped-by: GitHub Copilot\n\nClosing paragraph.\n",
            4,
        ),
        (
            "WP-01: add the workspace\n\nSigned-off-by: Anthropic Assistant <assistant@example.invalid>\n",
            4,
        ),
        (
            "WP-01: add the workspace\n\nBody text.\n\nRefs: WP-01\nTool: Codex\n",
            4,
        ),
        ("WP-01: add the workspace\n\nWritten by Claude.\n", 4),
        ("WP-01: add the workspace\n\n(created using Copilot)\n", 4),
        ("WP-01: add the workspace\n\nCo-authored by Claude\n", 4),
        ("WP-01: add the workspace \u{1F916}\n", 5),
        (
            "WP-01: add the workspace\r\n\r\nCo-authored-by: Claude <noreply@anthropic.com>\r\n",
            1,
        ),
        (
            "WP-01: add the workspace\n\n# ------------------------ >8 ------------------------\nCo-authored-by: Claude <noreply@anthropic.com>\n",
            1,
        ),
    ];

    /// The accepted cases of `.githooks/test-hooks.sh`.
    const ACCEPTED: &[&str] = &[
        "WP-56: Codex P1-P7 probes through the harness stub\n",
        "Claude Code: add the plugin wrapper to the harness stub\n",
        "Codex: record the commit-attribution behaviour\n\nCodex's apply_patch keeps the file id; Claude Code's Write tool does not.\nThe OpenAI tokenizer counts are taken offline.\n\nRefs: WP-03\n",
        "WP-58: headless Claude Code invocation with the model pinned\n",
        "WP-61: fold_v1 tables\n\nGenerated with\n",
        "WP-61: fold_v1 tables\n\nGenerated with xtask ucd from the pinned UCD 17.0.0 files.\nGenerated by the build script.\n",
        "WP-01: add the workspace\n\nSigned-off-by: Test Author <author@example.invalid>\nRefs: WP-01\n",
        "WP-03: refuse AI co-author trailers in commit-msg\n",
        "WP-54: token ratios\n\nThe Anthropic and OpenAI tokenizers differ on Cyrillic prose.\n\nMeasured on synthetic classes only.\n",
    ];

    #[test]
    fn hook_refusal_cases() {
        for (msg, rule) in REFUSED {
            let r = rules(msg);
            assert!(
                r.contains(rule),
                "expected rule {rule} for {msg:?}, got {r:?}"
            );
        }
    }

    #[test]
    fn hook_accepted_cases() {
        for msg in ACCEPTED {
            let r = check_message(msg, "", "#");
            assert!(r.is_empty(), "expected acceptance of {msg:?}, got {r:?}");
        }
    }

    #[test]
    fn verbose_diff_below_scissors_is_skipped() {
        let msg = "WP-03: add a synthetic file that quotes the refused markers\n\n# ------------------------ >8 ------------------------\n# Do not modify or remove the line above.\ndiff --git a/q.txt b/q.txt\n+Co-authored-by: Claude <noreply@anthropic.com>\n";
        assert!(check_message(msg, "", "#").is_empty());
    }

    #[test]
    fn git_trailer_parse_is_consulted() {
        let r = check_message("WP-01: x\n\nbody\n", "Tested-on: Codex", "#");
        assert_eq!(r.len(), 1);
        assert_eq!(r[0].rule, 4);
        assert!(check_message("WP-01: x\n", "Refs: WP-01", "#").is_empty());
    }

    #[test]
    fn boundaries() {
        assert!(!has_word(b"claudette", "claude"));
        assert!(has_word(b"(claude)", "claude"));
        assert!(has_gpt(b"gpt-4o"));
        assert!(has_gpt(b"gpt-5_x"));
        assert!(!has_gpt(b"gpt5_x"));
        assert!(!has_gpt(b"chatgptx"));
        assert!(has_vendor_address(b"a@mail.openai.com>"));
        assert!(!has_vendor_address(b"a@openai.com.evil"));
        assert!(!has_vendor_address(b"@anthropic.com"));
        assert!(has_vendor_address(b"copilot@github.com"));
        assert!(!has_vendor_address(b"xcopilot@github.com"));
        assert!(is_url(b"https://example.invalid/x"));
        assert!(!is_url(b"refs: x"));
        assert_eq!(
            check_identity("author", "Claude <noreply@anthropic.com>").len(),
            1
        );
        assert!(check_identity("author", "Owner <owner@example.invalid>").is_empty());
    }
}
